defaults:
  - user: gerstenecker
  - model: PlanT

# Logging
exp_folder_name: PlanTUpdate_Training
hydra:
  run:
    dir: outputs/${exp_folder_name}/${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    config:
      override_dirname:
        exclude_keys:
          - expname
        kv_sep: '='
        item_sep: '_'

# Train settings:
seed: 1
checkpoint_dir: /home/gerstenecker/CaRL/PlanT/FinalTrain
data_dir: /home/gerstenecker/PDM-Lite-DS
use_caching: True
gpus: 1
lrDecay_epoch: 45

wandb_name: PlanT_FinalTrain
debug: False
overfit: 0
resume: False
custom_sampler: False
