_target_: carl_nuplan.planning.gym.environment.reward_builder.default_reward_builder.DefaultRewardBuilder
_convert_: 'all'

environment_area: ${observation_builder.environment_area}

config:
  _target_: carl_nuplan.planning.gym.environment.reward_builder.default_reward_builder.DefaultRewardConfig
  _convert_: 'all'

  route_completion_type: "human"
  collision_type: "non_stationary"
  ttc_type: "v2"
  red_light_type: null
  lane_distance_type: "v1"
  off_route_type: "v1"
  comfort_type: "kinematics"

  comfort_accumulation: "value"
  ttc_accumulation: "value"
  reward_accumulation: "regular"


  terminal_penalty: 0.0
  collision_terminal_penalty: 0.0
  off_road_violation_threshold: 0.0
  lane_distance_violation_threshold: 0.5
  survival_ratio: 0.2

  reward_factor: 100.0
