_target_: carl_nuplan.planning.gym.environment.observation_builder.default.default_observation_builder.DefaultObservationBuilder
_convert_: 'all'

environment_area:
  _target_: carl_nuplan.planning.gym.environment.helper.environment_area.RectangleEnvironmentArea
  _convert_: 'all'

  front: 78.0
  back: 50.0
  left: 64.0
  right: 64.0

renderer:
  _target_: carl_nuplan.planning.gym.environment.observation_builder.default.default_renderer.DefaultRenderer
  _convert_: 'all'

  environment_area: ${observation_builder.environment_area}
  pixel_per_meter: 2.0
  max_vehicle_speed: 30.0
  max_pedestrian_speed: 4.0
  vehicle_scaling: 1.0
  pedestrian_scaling: 1.0
  static_scaling: 1.0
  include_speed_line: False
  lane_connector_route: False

obs_num_measurements: 10
num_value_measurements: 4
action_space_dim: 2
inference: False
