name: PlanT

training:
  max_epochs: 47
  batch_size: 128
  learning_rate: 1e-4
  betas: [0.9, 0.95]
  grad_norm_clip: 1.0
  weight_decay: 0.1 # only applied on matmul weights
  ckpt_path: log/
  num_workers: 20 # for DataLoader
  seq_len: 1
  pred_len: 4
  max_NextRouteBBs: 2 # max 10 prevents really high ids if route is long
  augment: False
  pretraining_path: none

  max_object_dist: 30

pre_training:
  # pretraining: forecast # Change: In this implementation we always use multitask training
  # multitask: True
  forecastLoss_weight: 0.2
  future_timestep: 1
  quantize: True
  precision_pos: 7 # 7: 0.5meters
  precision_speed: 5 # 4: 3.75km/h # changed from 4 to 5 bcs speed was changed from 60 to 120
  precision_angle: 5 # 5: 11.25degrees

network:
  hf_checkpoint: prajjwal1/bert-medium #prajjwal1/bert-tiny, prajjwal1/bert-mini, prajjwal1/bert-small, prajjwal1/bert-medium
  embd_pdrop: 0.1
