_target_: carl_nuplan.planning.gym.environment.trajectory_builder.action_trajectory_builder.ActionTrajectoryBuilder
_convert_: 'all'

scale_max_acceleration: 2.4
scale_max_deceleration: 3.2
scale_max_steering_angle: 0.83775804096
clip_max_abs_steering_rate: null
clip_max_abs_lon_jerk: null
clip_max_abs_yaw_accel: null
clip_angular_adjustment: False
convert_low_pass_acceleration: False
convert_low_pass_steering: False
disable_reverse_driving: True

# scale_max_acceleration: 2.4
# scale_max_deceleration: 4.0
# scale_max_steering_angle: 1.0471975512
# clip_max_abs_steering_rate: null
# clip_max_abs_lon_jerk: null
# clip_max_abs_yaw_accel: null
# clip_angular_adjustment: False
# convert_low_pass_acceleration: False
# convert_low_pass_steering: False
# disable_reverse_driving: True

# scale_max_acceleration: 2.4
# scale_max_deceleration: 4.0
# scale_max_steering_angle: 1.0471975512
# clip_max_abs_steering_rate: 0.5
# clip_max_abs_lon_jerk: 4.13
# clip_max_abs_yaw_accel: null
# clip_angular_adjustment: True
# convert_low_pass_acceleration: False
# convert_low_pass_steering: False
# disable_reverse_driving: True
